### ISSUE TITLE
New Project: JReleaser Azure DevOps extension

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1200]
Would be great to have an extension for Azure DevOps, similar to https://github.com/goreleaser/goreleaser-azure-devops-extension

**Comment by shblue21** [comment]
hello. Since seeing the issue, I've been working on JReleaser's Azure devops extension.
Basic functions have been implemented. When the work such as ci/cd and documents is completed, will you transfer the repository?

![image](https://user-images.githubusercontent.com/25363091/218349471-61cee50c-4c66-44f6-9fd6-037b1dc97e03.png)

**Comment by aalmiray** [comment]
Wow, this is amazing! 🤩 Thank you so much for your efforts. 

Regarding transfer of the codebase, yes, we can host it at the jreleaser github organization. If you agree we can apply the same rules as this repo that is, put the CLA in place, copyright transfers to JReleaser yet authorship of everything you wrote remains yours.

**Comment by shblue21** [comment]
Thank you for your feedback. When I'm done with the documentation, etc, I'll make the repository public.  
After, I will share with you a sample Azure Devops project with JReleaser extension applied.  

I will reply again within the next week at the latest.
Thank you for developing JReleaser.

**Comment by shblue21** [comment]
@aalmiray I apologize for the delay in replying. The work is mostly complete.

- I made the functionality available per task (e.g. init,config,release...) instead of simply using the CLI like GoReleaser.
- Most of the functionality is implemented, but there are still a few things left to do, like implementing mock tests, logging and error handling.
- I haven't put it on the MarketPlace yet. 

I'm a big fan of Azure DevOps and JReleaser, so it's been a pleasure working with it.
I apologize for the delay in replying, I would appreciate it if you could review it to see if it is of sufficient quality.

https://github.com/shblue21/jreleaser-azure-devops-extension

**Comment by aalmiray** [comment]
@shblue21 This is incredible! 🤩 

I do have some questions and comments:

 1.  What does the "custom" command do?
 2. Could "customArguments" be renamed to just "arguments"?
 3. Should "JReleaserExecuter" be renamed to "JReleaserInvoker"?
 4. The "template" command should be "template generate".

Thank you again for all this great work 🚀

**Comment by shblue21** [comment]
1. select a menuitem, such as assemble, if you want to enter a command without selecting it directly (e.g. release --dry-run) I'll rename it if necessary!
2. sure, I'll rename it.
3. of course! I'll change it right away.
4. I'll fix it, I made a mistake.

Thank you for your kind feedback.

**Comment by aalmiray** [comment]
@shblue21 I've sent you an invitation to join the JReleaser organization. Your role should give you access for transferring the repository whenever you feel like doing so (no rush 😄). Do let me know if access rights need to be adjusted.

**Comment by shblue21** [comment]
@aalmiray Hello. I've made some bug and feature fixes, and moved the repository.
Could you please grant me permission to the 'jreleaser-azure-devops-extension' repository?
I also created an Azure devops organization for JReleaser (for CI/CD) and invited you as an admin 
(you can decline if you feel it's unnecessary, feel free).
I also want to invite the extension 'Azure Devops Market Place Publisher' as an owner, see screenshot below and let me know the ID.  

-----------

![image](https://github.com/jreleaser/jreleaser/assets/25363091/2052fcb9-8dcc-4341-aa1c-ad95c85170f2)
1. log in to https://marketplace.visualstudio.com/
2. Hover over your account in the top right corner and you'll see your ID.

**Comment by aalmiray** [comment]
@shblue21 Done. You should have `admin` rights for 'jreleaser-azure-devops-extension'.
