### ISSUE TITLE
[core] Let the "early-access" tag name be configurable

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#275]

**Comment by cbeams** [comment]
only loosely related to this issue, but seeing it made me think of the following feedback.

the floating `early-access` tag approach is nice, but it does cause a negative user experience when fetching tags. users end up seeing error messages like:

```
git pull --tags
From https://github.com/MY/REPO
[...]
 ! [rejected]        early-access     -> early-access  (would clobber existing tag)
[...]
```

this is solved with `-f`, but that won't be obvious to the uninitiated.

there is also the possibility to set `tagOpts` on the remote with git config so that `-f` is always passed. That might be something worth documenting in the context of setting up early access releases.
