### ISSUE TITLE
[announce] jreleaser announce -y does not include sdkman

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#329]
In docs at https://jreleaser.org/guide/latest/configuration/packagers/sdkman.html it says

"  | Configuring this packager automatically enables the Sdkman announcer."

but when running ` jbang jreleaser-snapshot@jreleaser announce -y` I only get the ones that are explicitly listed:

```
[INFO]  Announcing release
[INFO]    [article] setting up repository jbangdev/jbang.dev
[INFO]    [twitter] Tweeting: JBang 0.78.0 has been released! https://github.com/jbangdev/jbang/releases/tag/v0.78.0
```

Do I need to continue using sdkman announcer to do the sdkman "Distro" ?

**Comment by aalmiray** [comment]
The bug is caused by https://github.com/jreleaser/jreleaser/blob/3894b1a2ae7d9dda981d4fb10131b59733b6100f/sdks/sdkman-java-sdk/src/main/java/org/jreleaser/sdk/sdkman/SdkmanAnnouncer.java#L62

As it expects the `sdkman` packager to have run before announce was invoked. This of course will happen when the `full-release` command is used but not when `announce` is used on its own.
